services:
  php81_cli:
    image: marol/crm_admin
    build:
      context: ./
      dockerfile: ./laravel.Dockerfile
    expose:
      - 8000
    ports:
      - "80:8000"
    tty: true
    stdin_open: true
    networks:
      - laravel_sail
    volumes:
      - ./packages:/var/www/html/package
networks:
  laravel_sail:
    external: true