services:
  php81_cli:
    image: marol/crm_admin
    build:
      context: ./
      dockerfile: ./laravel.Dockerfile
    expose:
      - 8000
    ports:
      - "80:8000"
    tty: true
    stdin_open: true
    volumes:
      - ./packages:/var/www/html/package
  mariadb_1011:
    image: mariadb:10.11.6-jammy
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root123
    volumes:
      - mariadb:/var/lib/mysql
volumes:
  mariadb: