services:
  php81:
    image: marol/crm_admin
    build:
      context: ./packages
      dockerfile: ../laravel.Dockerfile
    expose:
      - 8000
      - 6001
    ports:
      - "80:8000"
      - "6001:6001"
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www/html/package
  mariadb11:
    image: mariadb:11.2.2
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/mysql/lib
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MARIADB_DATABASE=laravel
volumes:
  mariadb-data: